export const initialUsersData = [
  {
    id: 'adv1',
    email: 'advertiser@example.com',
    password: 'password123',
    userType: 'advertiser',
    name: 'AdVert Corp',
    username: 'AdVertCorp',
    firstName: 'Ad',
    lastName: 'Corp',
    companyName: 'AdVert Corp Inc.',
    avatar: 'https://i.pravatar.cc/150?u=advertiser@example.com',
    bio: 'Leading provider of home service leads. Connecting homeowners with skilled professionals.',
    location: 'New York, NY',
    streetAddress: '123 Market St',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    country: 'USA',
    phone: '555-0100',
    memberSince: '2022-01-15T10:00:00.000Z',
    overallRating: 4.7,
    totalReviews: 120,
    stats: {
      totalJobsPosted: 150,
      activeJobs: 25,
      completionRate: 85,
      communicationRating: 4.8,
      jobClarityRating: 4.6,
      paymentReliability: 4.9,
    },
    settings: {
      notifications: { email: true, sms: false, push: true },
      theme: 'light',
      language: 'en',
      jobDefaults: {
        category: 'Plumbing',
        urgency: 'medium',
        profitSharePercentage: 50,
      },
      autoApproveTechnicians: false,
      blockedTechnicians: [],
      preferredTechnicians: [],
      leadShareSettings: {
        shareWithNetwork: true,
        networkRadius: 50, 
        autoShareDelay: 24 
      },
      pipelineStages: [
        { id: 'open', name: 'Open Leads', color: '#3B82F6' },
        { id: 'applied', name: 'Applications Received', color: '#F59E0B' },
        { id: 'assigned', name: 'Assigned', color: '#10B981' },
        { id: 'in_progress', name: 'In Progress', color: '#8B5CF6' },
        { id: 'completed', name: 'Completed', color: '#14B8A6' },
        { id: 'paid', name: 'Paid & Closed', color: '#6366F1' },
        { id: 'disputed', name: 'Disputed', color: '#EF4444' },
      ],
      tags: [
        { id: 'tag1', name: 'High Priority', color: '#EF4444' },
        { id: 'tag2', name: 'Requires Follow-up', color: '#F59E0B' },
        { id: 'tag3', name: 'VIP Customer', color: '#8B5CF6' },
      ],
      reminders: {
        upcomingJobs: { enabled: true, timing: '1_day_before' },
        quoteFollowUp: { enabled: false, timing: '3_days_after' },
        invoiceDue: { enabled: true, timing: '2_days_before' },
        newMessage: { enabled: true, timing: 'immediately' },
      },
      checklists: [
        {
          id: 'cl_default_1',
          name: 'Standard Pre-Job Check',
          items: [
            { id: 'cli_1_1', type: 'checkbox', label: 'Confirm appointment with customer', isRequired: true },
            { id: 'cli_1_2', type: 'text', label: 'Review job scope and materials needed', isRequired: true },
            { id: 'cli_1_3', type: 'notes', label: 'Any initial observations or concerns?', isRequired: false },
          ]
        }
      ]
    },
    jobTemplates: [
      { id: 'tpl_plumb_drain', name: 'Drain Cleaning (Plumbing)', category: 'Plumbing', description: 'Standard drain cleaning service for residential properties.', budget: 150, profitSharePercentage: 60, urgency: 'medium', checklistId: 'cl_default_1' },
      { id: 'tpl_elec_outlet', name: 'Outlet Replacement (Electrical)', category: 'Electrical', description: 'Replace faulty electrical outlet.', budget: 100, profitSharePercentage: 50, urgency: 'high', checklistId: null },
    ],
  },
  {
    id: 'tech1',
    email: 'technician1@example.com',
    password: 'password123',
    userType: 'technician',
    name: 'John Doe',
    username: 'JohnThePro',
    firstName: 'John',
    lastName: 'Doe',
    companyName: 'John\'s Pro Services',
    avatar: 'https://i.pravatar.cc/150?u=technician1@example.com',
    bio: 'Experienced technician specializing in plumbing and HVAC. Committed to quality work and customer satisfaction. 10+ years in the field.',
    location: 'Brooklyn, NY',
    streetAddress: '456 Oak Ave',
    city: 'Brooklyn',
    state: 'NY',
    zipCode: '11201',
    country: 'USA',
    phone: '555-0101',
    serviceArea: 'Brooklyn, Queens, Manhattan',
    skills: {
      'Plumbing': ['Drain Cleaning', 'Fixture Installation', 'Leak Repair', 'Water Heaters'],
      'HVAC': ['AC Repair', 'Furnace Maintenance', 'Thermostat Installation']
    },
    memberSince: '2021-05-20T09:00:00.000Z',
    overallRating: 4.9,
    totalReviews: 85,
    completedJobs: 120,
    yearsOfExperience: 10,
    insuranceDetails: 'General Liability $1M, Workers Comp',
    licenseNumber: 'LIC-12345XYZ',
    stats: {
      jobClosingRate: 88,
      customerServiceRating: 4.9,
      arrivalOnTimeRating: 4.8,
      responseTime: '2 hours',
      certifications: ['Master Plumber', 'EPA Certified'],
      specialties: ['Tankless Water Heaters', 'Smart Home HVAC'],
      jobsAppliedTo: 150,
    },
    settings: {
      notifications: { email: true, sms: true, push: true },
      theme: 'dark',
      language: 'en',
      availability: {
        monday: { start: '08:00', end: '17:00', enabled: true },
        tuesday: { start: '08:00', end: '17:00', enabled: true },
        wednesday: { start: '08:00', end: '17:00', enabled: true },
        thursday: { start: '08:00', end: '17:00', enabled: true },
        friday: { start: '08:00', end: '17:00', enabled: true },
        saturday: { start: '10:00', end: '15:00', enabled: false },
        sunday: { start: '10:00', end: '15:00', enabled: false },
      },
      serviceRadius: 30, 
      blockedAdvertisers: [],
      preferredCategories: ['Plumbing', 'HVAC'],
      reminders: {
        upcomingJobs: { enabled: true, timing: '1_hour_before' },
        reviewLeads: { enabled: true, timing: 'daily_9am' },
        updatePipeline: { enabled: false, timing: 'weekly_monday' },
        newMessage: { enabled: true, timing: 'immediately' },
      },
    }
  },
  {
    id: 'tech2',
    email: 'technician2@example.com',
    password: 'password123',
    userType: 'technician',
    name: 'Alice Smith',
    username: 'AliceFixIt',
    firstName: 'Alice',
    lastName: 'Smith',
    companyName: 'Alice\'s Electrical Solutions',
    avatar: 'https://i.pravatar.cc/150?u=technician2@example.com',
    bio: 'Certified electrician with a focus on residential and commercial projects. Quick, reliable, and efficient.',
    location: 'Queens, NY',
    streetAddress: '789 Pine Ln',
    city: 'Queens',
    state: 'NY',
    zipCode: '11354',
    country: 'USA',
    phone: '555-0102',
    serviceArea: 'Queens, Long Island',
    skills: {
      'Electrical': ['Wiring', 'Panel Upgrades', 'Lighting Installation', 'Smart Home Setup'],
      'Handyman': ['Minor Repairs', 'Fixture Assembly']
    },
    memberSince: '2023-01-10T14:30:00.000Z',
    overallRating: 4.7,
    totalReviews: 45,
    completedJobs: 60,
    yearsOfExperience: 5,
    insuranceDetails: 'General Liability $500k',
    licenseNumber: 'LIC-ELECTRO-ALICE',
    stats: {
      jobClosingRate: 82,
      customerServiceRating: 4.8,
      arrivalOnTimeRating: 4.6,
      responseTime: '4 hours',
      certifications: ['Master Electrician'],
      specialties: ['EV Charger Installation', 'LED Lighting Retrofits'],
      jobsAppliedTo: 90,
    },
    settings: {
      notifications: { email: true, sms: false, push: false },
      theme: 'light',
      language: 'en',
      availability: {
        monday: { start: '09:00', end: '18:00', enabled: true },
        tuesday: { start: '09:00', end: '18:00', enabled: true },
        wednesday: { start: '09:00', end: '18:00', enabled: true },
        thursday: { start: '09:00', end: '18:00', enabled: true },
        friday: { start: '09:00', end: '16:00', enabled: true },
        saturday: { start: '10:00', end: '14:00', enabled: true },
        sunday: { start: '10:00', end: '14:00', enabled: false },
      },
      serviceRadius: 25,
      blockedAdvertisers: ['adv1'],
      preferredCategories: ['Electrical'],
      reminders: {
        upcomingJobs: { enabled: true, timing: '2_hours_before' },
        reviewLeads: { enabled: false, timing: 'daily_9am' },
        newMessage: { enabled: true, timing: 'immediately' },
      },
    }
  },
  {
    id: 'avi_user',
    email: 'avi@gmail.com',
    password: '12345',
    userType: 'advertiser',
    name: 'Avi TestUser',
    username: 'AviTest',
    firstName: 'Avi',
    lastName: 'TestUser',
    companyName: 'Avi Test Corp Inc.',
    avatar: 'https://i.pravatar.cc/150?u=avi@gmail.com',
    bio: 'Test user for ServiceHub. Exploring features.',
    location: 'Test City, TS',
    streetAddress: '1 Test Way',
    city: 'Test City',
    state: 'TS',
    zipCode: '00000',
    country: 'Testland',
    phone: '555-0199',
    memberSince: new Date().toISOString(),
    overallRating: 5.0,
    totalReviews: 1,
    stats: {
      totalJobsPosted: 1,
      activeJobs: 0,
      completionRate: 100,
      communicationRating: 5.0,
      jobClarityRating: 5.0,
      paymentReliability: 5.0,
    },
    settings: {
      notifications: { email: true, sms: false, push: true },
      theme: 'light',
      language: 'en',
      jobDefaults: { category: 'Other', urgency: 'low', profitSharePercentage: 50, },
      autoApproveTechnicians: true,
      blockedTechnicians: [],
      preferredTechnicians: [],
      leadShareSettings: { shareWithNetwork: false, networkRadius: 10, autoShareDelay: 0 },
      pipelineStages: [ { id: 'open', name: 'Open Leads', color: '#3B82F6' }, ],
      tags: [],
      reminders: { upcomingJobs: { enabled: false, timing: '1_day_before' }, newMessage: { enabled: true, timing: 'immediately' }, },
      checklists: []
    },
    jobTemplates: [],
  },
  {
    id: 'tech_avizadok55',
    email: 'avizadok55@gmail.com',
    password: '12345',
    userType: 'technician',
    name: 'Avi Zadok',
    username: 'AviTheTechnician',
    firstName: 'Avi',
    lastName: 'Zadok',
    companyName: 'Avi\'s Pro Tech Services',
    avatar: 'https://i.pravatar.cc/150?u=avizadok55@gmail.com',
    bio: 'Dedicated service professional ready to tackle any job. Specializing in general repairs and installations.',
    location: 'Miami, FL',
    streetAddress: '123 Sunshine Blvd',
    city: 'Miami',
    state: 'FL',
    zipCode: '33101',
    country: 'USA',
    phone: '555-0255',
    serviceArea: 'Miami-Dade County',
    skills: {
      'Handyman': ['General Repairs', 'Painting', 'Fixture Installation', 'Drywall Patching'],
      'Assembly': ['Furniture Assembly', 'Equipment Setup']
    },
    memberSince: new Date().toISOString(),
    overallRating: 0,
    totalReviews: 0,
    completedJobs: 0,
    yearsOfExperience: 3,
    insuranceDetails: 'Pending',
    licenseNumber: 'Pending',
    stats: {
      jobClosingRate: 0,
      customerServiceRating: 0,
      arrivalOnTimeRating: 0,
      responseTime: 'N/A',
      certifications: [],
      specialties: ['Quick Turnaround', 'Customer Friendly'],
      jobsAppliedTo: 0,
    },
    settings: {
      notifications: { email: true, sms: true, push: true },
      theme: 'light',
      language: 'en',
      availability: {
        monday: { start: '09:00', end: '17:00', enabled: true },
        tuesday: { start: '09:00', end: '17:00', enabled: true },
        wednesday: { start: '09:00', end: '17:00', enabled: true },
        thursday: { start: '09:00', end: '17:00', enabled: true },
        friday: { start: '09:00', end: '17:00', enabled: true },
        saturday: { start: '10:00', end: '14:00', enabled: false },
        sunday: { start: '10:00', end: '14:00', enabled: false },
      },
      serviceRadius: 20, 
      blockedAdvertisers: [],
      preferredCategories: ['Handyman', 'Assembly'],
      reminders: {
        upcomingJobs: { enabled: true, timing: '1_hour_before' },
        reviewLeads: { enabled: true, timing: 'daily_10am' },
        newMessage: { enabled: true, timing: 'immediately' },
      },
    }
  }
];

export const createNewUserObject = (userData) => {
  const nameParts = userData.name.split(' ');
  const firstName = nameParts[0] || '';
  const lastName = nameParts.slice(1).join(' ') || '';

  return {
    id: `user_${Date.now()}`,
    name: userData.name,
    username: userData.username,
    email: userData.email,
    password: userData.password, 
    userType: userData.userType,
    firstName,
    lastName,
    phone: userData.phone || '',
    location: userData.location || '',
    streetAddress: '',
    aptSuite: '',
    city: userData.location ? userData.location.split(',')[0]?.trim() : '',
    state: userData.location ? userData.location.split(',')[1]?.trim() : '',
    zipCode: '',
    country: '',
    companyName: userData.userType === 'advertiser' ? `${userData.name}'s Company` : (userData.userType === 'technician' ? `${userData.name}'s Services` : ''),
    avatar: `https://avatar.vercel.sh/${userData.username || userData.name}.png?size=150`,
    bio: `Welcome ${userData.name}! Ready to get started.`,
    memberSince: new Date().toISOString(),
    overallRating: 0,
    totalReviews: 0,
    completedJobs: 0,
    stats: userData.userType === 'technician' ? {
      jobClosingRate: 0, customerServiceRating: 0, arrivalOnTimeRating: 0, responseTime: 'N/A', certifications: [], specialties: [], jobsAppliedTo: 0,
    } : {
      totalJobsPosted: 0, activeJobs: 0, completionRate: 0, communicationRating: 0, jobClarityRating: 0, paymentReliability: 0,
    },
    settings: userData.userType === 'technician' ? {
      notifications: { email: true, sms: false, push: false }, theme: 'light', language: 'en', availability: {}, serviceRadius: 10, blockedAdvertisers: [], preferredCategories: [], reminders: { newMessage: { enabled: true, timing: 'immediately' }}
    } : {
      notifications: { email: true, sms: false, push: false }, theme: 'light', language: 'en', jobDefaults: {}, autoApproveTechnicians: false, blockedTechnicians: [], preferredTechnicians: [], leadShareSettings: {}, pipelineStages: [], tags: [], reminders: { newMessage: { enabled: true, timing: 'immediately' }}, checklists: []
    },
    jobTemplates: userData.userType === 'advertiser' ? [] : undefined,
    skills: userData.userType === 'technician' ? {} : undefined,
  };
};